name: log_custom_printer
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  test: ^1.25.6
