name: log_custom_printer
description: A custom log printer for Flutter applications.
version: 1.1.1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.11.0
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
  test: ^1.29.0
