name: log_custom_printer
description: A custom log printer for Flutter applications.
version: 2.0.0

environment:
  sdk: ^3.11.0

dependencies:
  get_it: ^9.2.1
  meta: ^1.17.0
  json_annotation: ^4.11.0

  path: ^1.9.1

dev_dependencies:
  lints: ^6.1.0
  build_runner: ^2.11.1
  json_serializable: ^6.13.0
  test: ^1.29.0
